services:
  app:
    build: .
    container_name: caching
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
